# Generated by Django 3.0.6 on 2020-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(default='Bengaluru', max_length=250),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website_url',
            field=models.URLField(default='#', max_length=250),
        ),
    ]
