# Generated by Django 3.0.6 on 2020-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200512_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
