# Generated by Django 3.0.6 on 2020-05-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cities', '0001_initial'),
        ('companies', '0003_auto_20200512_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='city_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_cities.City'),
        ),
    ]
