# Generated by Django 3.0.6 on 2020-05-16 15:15

from django.db import migrations

def link_cities(apps, schema_editor):
    CompanyProfile = apps.get_model('companies', 'CompanyProfile')
    City = apps.get_model('custom_cities', 'City')
    for cp in CompanyProfile.objects.all():
        if(cp.city is not None and cp.user is not None):
            city, created = City.objects.get_or_create(name=cp.city)
            cp.city_link = city
            cp.save()

def unlink_cities(apps, schema_editor):
    CompanyProfile = apps.get_model('companies', 'CompanyProfile')
    City = apps.get_model('custom_cities', 'City')
    for cp in CompanyProfile.objects.all():
        cp.city_link = None
        cp.save()



class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_city_link'),
    ]

    operations = [
        migrations.RunPython(link_cities, unlink_cities),
    ]
