# Generated by Django 3.0.6 on 2020-05-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_transfer_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='city',
        ),
    ]
