# Generated by Django 3.0.6 on 2020-05-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_companyprofile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='city_link',
            new_name='city',
        ),
    ]
