# Generated by Django 3.0.6 on 2020-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20200516_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_field',
            field=models.CharField(choices=[('DF', 'IT, Consulting and Product Development'), ('ED', 'Engineering and Design'), ('LB', 'Local Business')], default='DF', max_length=100),
        ),
    ]
